language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk12

#ignore default install step
install: true

#cache dependencies
cache:
  directories:
    - $HOME/.m2/repository

script: ./mvnw clean verify

